### PR TITLE
Class box element prototype

### PR DESCRIPTION
**Pull request by em66850**

### CODE REVIEW

**Comment by em66850** [comment]
Class box is working and formatted correctly, but the middle sections proportions cannot be adjusted currently. 

There is also an issue where the movement preview shows that the rectangle fill extends outside of the border. It can only be seen when the move preview's fill color is not set to transparent.

**Comment by em66850** [comment]
Created a new issue for section resizing, logic for this PR is done but tests need to be added.

**Comment by em66850** [comment]
Resolves #83

**Review by Andrei486 — APPROVED** [review]
Looks good! Application runs and tests pass on my end. I found a bug related to the EditableLabelController while testing this issue, but it's not breaking nor is it introduced here (I'm pretty sure). Going to create a separate issue for that bug, this is good to merge as far as I'm concerned.

**Pull request merged**
