### PR TITLE
Make text styling UI functional

### LINKED ISSUE #101: Make text styling UI functional
Currently the font family, style, and size options in the editor do not do anything. Implement their functionality. For now, one style per editable label is fine.

### PR DESCRIPTION
**Pull request by em66850**
Resolves #101

### CODE REVIEW

**Comment by em66850** [comment]
Code cleanup, docs, and tests in progress.

**Comment by em66850** [comment]
Known issues:
- save/load needs to be implemented for styling
- when the formatting panel options are used, the element loses focus which makes it annoying to use

**Comment by Andrei486** [comment]
The commands work when sent between users, the correct styling is applied to the element. However, the formatting panel's fields do not update: this is because the formatting panel only updates when the active editable label is changed. There are two possible ways to fix this:

- Have the command manually call the formatting panel's update method. This would require passing the formatting panel into the command factory, creating a circular dependency which we'll need a setter method for. It should work though.
- Have the formatting panel and command respectively read/write to another model, which stores the styling information for the currently edited label (could be EditableLabelTracker), then have the FormattingPanelController register change listeners to that model as needed. This makes it so there is no need to manually update the formatting panel when something changes, as long as the model is updated correctly.

More notes on the model approach. When the currently edited label is changed, the field/button values should be recalculated, the same way that FormattingPanelController currently does. Additionally, the styling command should have access to the model (passed in via its factory) and should update the specific properties changed **only** if the target label is the one that the model is storing information for. The formatting panel should still ensure that all its fields are disabled when no label is selected, and should have change listeners for the other model properties as well (it should probably be one change listener that re-updates all the fields like it currently does). It may not have to recalculate the field values to set because the model should already that; alternatively the formatting panel could be put in charge of doing that recalculation and updating the model when the editable label changes, though I think this would only make sense if the model is separate from the EditableLabelTracker.

**Review by Andrei486 — APPROVED** [review]
Approving because I've seen the changes used and help test them, pretty sure we covered every case we can think of. I know some tests are in progress, once some of those are done we can merge whenever.

**Comment by Andrei486** [comment]
The last commit is an attempt to resolve #119 .

**Pull request merged**
